/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as PSlugRouteImport } from './routes/p/$slug'
import { Route as ApplySlugRouteImport } from './routes/apply/$slug'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAcademicsRouteImport } from './routes/app/academics'
import { Route as AppAnnouncementsRouteImport } from './routes/app/announcements'
import { Route as AppAttendanceRouteImport } from './routes/app/attendance'
import { Route as AppBehaviourRouteImport } from './routes/app/behaviour'
import { Route as AppFinanceRouteImport } from './routes/app/finance'
import { Route as AppPeopleRouteImport } from './routes/app/people'
import { Route as AppPlatformRouteImport } from './routes/app/platform'
import { Route as AppResultsRouteImport } from './routes/app/results'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSetupRouteImport } from './routes/app/setup'
import { Route as AppInvoicesRouteImport } from './routes/app/invoices'
import { Route as AppAdmissionsRouteImport } from './routes/app/admissions'
import { Route as AppToolsRouteImport } from './routes/app/tools'
import { Route as AppDocumentsRouteImport } from './routes/app/documents'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppStudentsRouteImport } from './routes/app/students'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPaychanguWebhookRouteImport } from './routes/api/paychangu/webhook'
import { Route as AppStudentsStudentIdRouteImport } from './routes/app/students.$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySlugRoute = ApplySlugRouteImport.update({
  id: '/apply/$slug',
  path: '/apply/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAcademicsRoute = AppAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBehaviourRoute = AppBehaviourRouteImport.update({
  id: '/behaviour',
  path: '/behaviour',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlatformRoute = AppPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdmissionsRoute = AppAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaychanguWebhookRoute = ApiPaychanguWebhookRouteImport.update({
  id: '/api/paychangu/webhook',
  path: '/api/paychangu/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AppStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/p/$slug': typeof PSlugRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/app/academics': typeof AppAcademicsRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/behaviour': typeof AppBehaviourRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/people': typeof AppPeopleRoute
  '/app/platform': typeof AppPlatformRoute
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/students': typeof AppStudentsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paychangu/webhook': typeof ApiPaychanguWebhookRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/p/$slug': typeof PSlugRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/app/academics': typeof AppAcademicsRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/behaviour': typeof AppBehaviourRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/people': typeof AppPeopleRoute
  '/app/platform': typeof AppPlatformRoute
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/students': typeof AppStudentsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paychangu/webhook': typeof ApiPaychanguWebhookRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/set-password': typeof SetPasswordRoute
  '/p/$slug': typeof PSlugRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/app/academics': typeof AppAcademicsRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/behaviour': typeof AppBehaviourRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/people': typeof AppPeopleRoute
  '/app/platform': typeof AppPlatformRoute
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/students': typeof AppStudentsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/paychangu/webhook': typeof ApiPaychanguWebhookRoute
  '/app/students/$studentId': typeof AppStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/set-password'
    | '/p/$slug'
    | '/app/academics'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/behaviour'
    | '/app/finance'
    | '/app/people'
    | '/app/platform'
    | '/app/results'
    | '/app/settings'
    | '/app/setup'
    | '/app/invoices'
    | '/app/calendar'
    | '/app/students'
    | '/app/'
    | '/api/auth/$'
    | '/app/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/set-password'
    | '/p/$slug'
    | '/app/academics'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/behaviour'
    | '/app/finance'
    | '/app/people'
    | '/app/platform'
    | '/app/results'
    | '/app/settings'
    | '/app/setup'
    | '/app/invoices'
    | '/app/calendar'
    | '/app/students'
    | '/app'
    | '/api/auth/$'
    | '/app/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/set-password'
    | '/p/$slug'
    | '/app/academics'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/behaviour'
    | '/app/finance'
    | '/app/people'
    | '/app/platform'
    | '/app/results'
    | '/app/settings'
    | '/app/setup'
    | '/app/invoices'
    | '/app/calendar'
    | '/app/students'
    | '/app/'
    | '/api/auth/$'
    | '/app/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetPasswordRoute: typeof SetPasswordRoute
  PSlugRoute: typeof PSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/academics': {
      id: '/app/academics'
      path: '/academics'
      fullPath: '/app/academics'
      preLoaderRoute: typeof AppAcademicsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/behaviour': {
      id: '/app/behaviour'
      path: '/behaviour'
      fullPath: '/app/behaviour'
      preLoaderRoute: typeof AppBehaviourRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/platform': {
      id: '/app/platform'
      path: '/platform'
      fullPath: '/app/platform'
      preLoaderRoute: typeof AppPlatformRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/results': {
      id: '/app/results'
      path: '/results'
      fullPath: '/app/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admissions': {
      id: '/app/admissions'
      path: '/admissions'
      fullPath: '/app/admissions'
      preLoaderRoute: typeof AppAdmissionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tools': {
      id: '/app/tools'
      path: '/tools'
      fullPath: '/app/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/students/$studentId': {
      id: '/app/students/$studentId'
      path: '/$studentId'
      fullPath: '/app/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppStudentsRoute
    }
  }
}

interface AppStudentsRouteChildren {
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsStudentIdRoute: AppStudentsStudentIdRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppRouteRouteChildren {
  AppAcademicsRoute: typeof AppAcademicsRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBehaviourRoute: typeof AppBehaviourRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppPlatformRoute: typeof AppPlatformRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAcademicsRoute: AppAcademicsRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBehaviourRoute: AppBehaviourRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppPlatformRoute: AppPlatformRoute,
  AppResultsRoute: AppResultsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSetupRoute: AppSetupRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SetPasswordRoute: SetPasswordRoute,
  PSlugRoute: PSlugRoute,
  ApplySlugRoute: ApplySlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaychanguWebhookRoute: ApiPaychanguWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
